services:
  mariadb:
    container_name: saus-mariadb
    image: mariadb:11
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: pass
    volumes:
      - mariadb_data:/var/lib/mysql
  redis:
    container_name: saus-redis
    image: redis:7-alpine
    ports:
      - 6379:6379

volumes:
  mariadb_data: {}
