version: "3.4"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.11
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: pass
  redis:
    container_name: redis
    image: redis:7.0-alpine
    ports:
      - 6379:6379

volumes:
  mongo-volume: {}
