apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: saus
bases:
  - ../base

resources:
  - ns.yaml
  - ss.yaml

commonAnnotations:
  domain: sausl.ink
  cert: saus-cert

patchesStrategicMerge:
  - patch.yaml
