---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saus-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
        - name: mariadb
          image: mariadb:10-focal
          resources:
            requests:
              memory: 200Mi
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_DATABASE
              value: saus
            - name: MARIADB_USER
              value: saus
            - name: MARIADB_PASSWORD
              value: saus
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "yes"
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: data-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: saus-db
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
