apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: saus-dev
bases:
  - ../base

resources:
  - db.yaml
  - ns.yaml
  - ss.yaml

configMapGenerator:
  - name: saus-django
    files:
      - settings.py

commonAnnotations:
  domain: dev.sausl.ink
  cert: saus-dev-cert

patchesStrategicMerge:
  - patch.yaml
