---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saus
spec:
  template:
    spec:
      initContainers:
        - name: saus-gunicorn-init
          image: ghcr.io/raynix/saus:dev-1132143054
      containers:
        - name: saus-gunicorn
          image: ghcr.io/raynix/saus:dev-1132143054

---
apiVersion: batch/v1
kind: Job
metadata:
  name: saus
spec:
  template:
    spec:
      containers:
        - name: saus-gunicorn-job
          image: ghcr.io/raynix/saus:dev-1132143054
