apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: django
  namespace: saus-dev
spec:
  encryptedData:
    DJANGO_SETTINGS_MODULE: AgDMTqtSkk3IzKRhD56P8t54FDiac24rT1rhpiY5cVpsHT1mY3gPQCnAS5IoRfYRFqgdj76oOV1lWDgzwJUm5uoWLXHy2P5jN7QtwDfxw3qEf23nzK6CjbouhSL0Hskh8P6fqbRBgEpovMGJF5A22pVrmSuGx8ZntrBYPc3td7TIJvcnm6dfVVEyt0p5nfJMLi8uZxMYbO+YzBpR6EPeZbdYzAxS97Jbau3UJxRh1IxFf5R9chbcAMZmqTychHuXltdXyb/PacAzS8QBwz7prbsQvHkbYHHbM2fB/RXBp1obG27cgMVAMu3q1vMdVZXFtbLwDVnWES5NbxNunFVXk61tE1nQmXbsKokMPUqnmQ8LgcFFhbLiJ1kV22UVxJp4fcvo0iW1CQpFzCLWby22kwJe1aat2S3CiLcInrjFkMqNjHqLsFoGCfkXlaRVklB2O8Ed9Sy75YHG9bQOtYFt0OAjGLRt/EtS+02TrqYZG96+xlz0GC+kCC9w6oUluAZAtdT0UJ3bAxe45xDVWYnquNfejLy7GgJb6RY9iPcunkBB8Oc3I2FUKFr52uLICVOhbE/sp23i18dvJaH3oihUu8+iKok+nv3HlL/Tl3xby0ERxQ1nRXTBvLdJM6JRL47cHRnkBtTVS1BRUuPZzVZpSvecPOC+/qcuAt6Ir83Gzl0CiMID1eqQglzdVuKoBezzkxUlD4dJV6nj+pboeKjT
    SECRET_KEY: AgANFR73Of6DwWSk/UtNbtBD+w2jo6LmZtyF/57JFhXpAMzg9B4hQRRBSBtJWUSV04P02peVtW2H8wkZRJxbIDfVtcRLE0Y+dNfOZPwm+49x02qGPBzF7wQctaAfNKTZ4xTHijCQeO9jH1V0ZbD6OawE5ihwcouMvfLfY33AHzJXb3DJqRaCQXpA0YG2NIQOM8iTfzt3OZo6hX3ZgVThiqrpB0nGOv9MnJeGYWyf6iJpULCHaf3VaOyCig3THa5NZhvOGqF1abDaAztE/lYhgH++Ge+98YLOUhYBuwLDu/UqpWsmhnROzp0yWCPvOhPkjL1w2eoJYq+nyEmYyQCQmVkGHxpHEq+Oc3rvJI7tKKmmrLYclgpkjj8MFjvLGx6ZQrEPTG2bJmLW6Mjkjno1szpVq6tszJ2UDHvox2YWQ1LL25iIPAw4A83fIbWYF5CR2iNdeV+lNM3gQrtDR61ksv75osJ3atOKCOCiMelo1aPYZtROW0uQV/LC6OAsPbXgoIzxa8hYffl/TlwwBzZaISvpvTY4DBhbwqs2S0IjPTdEqYyucRW72CbTyrePqfjS9HaT5BfpmqN5Ms3XPopqbwHwyq2Ol1u+WZSzVuGqZJRb0dqg2y8w8wg5eXPgqERmA4hQZgI1iEOk0T8hvrav+dspoMa34Hlg1Wy43wp9urzr8BJ3QCbrNuAkMU9eD+PiXQ8kxizOdwisCFs6CRh1RJSu505PFezSGKN96jJqAqHGErCY9WKOfzzAdfEa
  template:
    metadata:
      creationTimestamp: null
      name: django
      namespace: saus-dev
status: {}
