---
apiVersion: batch/v1
kind: Job
metadata:
  name: saus
spec:
  template:
    metadata:
      name: saus
      labels:
        app: saus
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
        - name: saus-gunicorn-job
          image: ghcr.io/raynix/saus:v0.2
          command:
            - django-admin
          args:
            - migrate
          volumeMounts:
            - name: saus-config-volume
              mountPath: /var/www/saus/saus/settings.py
              subPath: settings.py
          envFrom:
            - secretRef:
                name: django
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
      volumes:
        - name: nginx-config-volume
          configMap:
            name: saus-nginx
        - name: saus-config-volume
          configMap:
            name: saus-django
