apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - conf.yaml

resources:
  - job.yaml
  - deploy.yaml
  - service.yaml
  - redis.yaml
  - gateway.yaml
  - virtual-service.yaml

configMapGenerator:
  - name: saus-nginx
    files:
      - nginx-saus.conf

vars:
  - name: DOMAIN
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: saus
    fieldref:
      fieldpath: metadata.annotations.domain
  - name: CERT
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: saus
    fieldref:
      fieldpath: metadata.annotations.cert
