# This is a basic workflow to help you get started with Actions

name: Release with a tag

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  create:
    ref_types: tag

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ ubuntu-20.04 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: prepare the tag
        run: |
          ref=${{ github.ref }}
          if [[ $ref =~ refs\/tags\/ ]]; then
            echo "build_version=${ref#refs/tags/}" >> $GITHUB_ENV
          else
            echo "No tag found. Skipping."
            exit 1
          fi

      - name: Docker build saus-gunicorn
        run: |
          docker build -t ghcr.io/raynix/saus:$build_version .

      - name: Docker push
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/raynix/saus:$build_version

      - name: Update deployment version
        run: |
          sed -i -E "s|(image: ghcr.io/raynix/saus:).*|\1$build_version|g" .kustomize/sausl.ink/patch.yaml

      - name: Auto commit & push changes
        run: |
          git config --global user.name 'raynix Bot'
          git config --global user.email 'raynix@gmail.com'
          git commit -am "Automated commit"
          git push
